runtime: python311
instance_class: F1
service: rrhh-personal-api-key
entrypoint: gunicorn -w 2 -k uvicorn.workers.UvicornWorker rrhh_personal.app:create_app
env_variables:
  PROJECT_ID: justicia-digital-gob-mx
  SERVICE_PREFIX: pjecz_rrhh_personal_api_key
vpc_access_connector:
  name: projects/justicia-digital-gob-mx/locations/us-west2/connectors/cupido
